In [1]:
import pandas as pd
import numpy as np
import os

In [3]:
mortality_training_data = pd.read_csv('Data\\use_in_project\\mortality_training_data.csv')
mortality_training_data.head()

,customer_id,age,gender,height_cm,weight_kg,bmi,bmi_category,occupation,occupation_risk,smoker_status,...,base_mortality_probability,bmi_multiplier,occupation_multiplier,lifestyle_multiplier,health_multiplier,medical_extra_loading,mortality_probability,mortality_score,mortality_category,mortality_event
0,MORT0000001,44,Female,153.4,52.4,22.3,Normal Weight,Demolition Worker,High,0,...,0.002345,1.00,2.4,1.0500,0.85,0.0,0.004270,21.35,Low,0
1,MORT0000002,28,Male,170.3,99.8,34.4,Obese Class I,Real Estate Agent,Medium,1,...,0.000942,1.50,1.2,1.8375,1.00,0.0,0.003583,17.92,Low,0
2,MORT0000003,50,Male,165.5,76.9,28.1,Overweight,Racing Driver (Professional),High,0,...,0.004436,1.15,2.6,1.0500,0.85,0.0,0.013613,39.36,Medium,0
3,MORT0000004,52,Male,173.1,73.8,24.6,Normal Weight,Armed Forces Personnel (Combat),High,0,...,0.005550,1.00,2.5,0.9500,0.85,0.0,0.012885,38.14,Medium,0
4,MORT0000005,18,Female,162.2,50.6,19.2,Normal Weight,Teacher,Low,0,...,0.000874,1.00,1.0,1.0500,0.85,0.0,0.000663,3.32,Low,0

In [4]:
mortality_training_data.columns

Index(['customer_id', 'age', 'gender', 'height_cm', 'weight_kg', 'bmi',
       'bmi_category', 'occupation', 'occupation_risk', 'smoker_status',
       'alcohol_use', 'exercise_level', 'diabetes', 'hypertension',
       'heart_disease', 'respiratory_disease', 'cancer_history',
       'health_status', 'base_mortality_probability', 'bmi_multiplier',
       'occupation_multiplier', 'lifestyle_multiplier', 'health_multiplier',
       'medical_extra_loading', 'mortality_probability', 'mortality_score',
       'mortality_category', 'mortality_event'],
      dtype='str')

In [5]:
print(mortality_training_data.value_counts(['age', 'gender', 'bmi_category', 'mortality_score']))

age  gender  bmi_category   mortality_score
18   Female  Normal Weight  3.32               25
41   Female  Normal Weight  6.88               25
     Male    Normal Weight  9.31               24
18   Male    Normal Weight  4.49               24
38   Female  Normal Weight  5.51               23
                                               ..
39   Female  Overweight     33.49               1
46   Male    Overweight     24.11               1
48   Female  Obese Class I  47.94               1
62   Female  Obese Class I  77.42               1
57   Female  Obese Class I  37.52               1
Name: count, Length: 34751, dtype: int64

In [6]:
persistency_training_data = pd.read_csv('Data\\use_in_project\\persistency_training_data.csv')
persistency_training_data.head()

,policy_id,age,annual_income,dependents,existing_life_coverage,outstanding_loans,desired_coverage,recommended_coverage,product_id,product_name,...,years_since_issue,mortality_score,base_rate_per_thousand,premium_amount,premium_income_ratio,coverage_income_ratio,lapse_probability,persistency_risk_score,persistency_risk_category,lapse_flag
0,POL0000001,43,815000,0,0,2520000,9300000,10670000,LIC-WL-213,Enduring Security Whole Life - Series E,...,19,25.78,18.4,65182.41,0.0800,2.9202,0.0824,8.24,Low,1
1,POL0000002,18,641100,0,0,70000,7320000,6480000,LIC-U-160,Bluechip Multiplier ULIP,...,0,1.00,36.0,22190.84,0.0346,1.2167,0.1706,17.06,Low,1
2,POL0000003,48,394700,1,1530000,490000,6160000,2910000,LIC-MB-191,Cash Flow Life Plan (Series B),...,10,40.63,48.0,20210.50,0.0512,0.6081,0.0901,9.01,Low,0
3,POL0000004,57,453000,3,0,440000,6210000,4970000,LIC-WL-197,Heritage Wealth & Life - Series C,...,15,37.06,15.2,45976.93,0.1015,3.4658,0.0916,9.16,Low,0
4,POL0000005,34,563600,1,0,0,5180000,5640000,LIC-TL-187,Cancer Shield (Series F) Term,...,6,28.42,5.0,37102.48,0.0658,10.0071,0.1268,12.68,Low,0

In [7]:
persistency_training_data.columns

Index(['policy_id', 'age', 'annual_income', 'dependents',
       'existing_life_coverage', 'outstanding_loans', 'desired_coverage',
       'recommended_coverage', 'product_id', 'product_name', 'product_type',
       'product_risk_profile', 'coverage_amount', 'coverage_adequacy_ratio',
       'policy_term', 'payment_mode_preference', 'payment_mode',
       'autopay_preference', 'autopay_enabled', 'years_since_issue',
       'mortality_score', 'base_rate_per_thousand', 'premium_amount',
       'premium_income_ratio', 'coverage_income_ratio', 'lapse_probability',
       'persistency_risk_score', 'persistency_risk_category', 'lapse_flag'],
      dtype='str')

In [8]:
persistency_training_data.value_counts('persistency_risk_category')

persistency_risk_category
Low       43140
Medium     6250
High        552
Severe       58
Name: count, dtype: int64

In [9]:
product_catalog_sc_new = pd.read_csv('backend\\data\\product_catalog_sc_new.csv')

print(product_catalog_sc_new.columns.tolist())
print(product_catalog_sc_new.head())

['product_id', 'product_name', 'product_type', 'min_age', 'max_age', 'min_coverage', 'max_coverage', 'premium_paying_term_min', 'premium_paying_term_max', 'key_benefit', 'benefit_2', 'benefit_3', 'risk_profile', 'base_premium_rate']
   product_id              product_name product_type  min_age  max_age  \
0  LIC-TL-100    SecureShield Term Plan    Term Life       18       65
1  LIC-WL-101  LifeLong Prosperity Plan   Whole Life       18       60
2   LIC-E-102  Wealth Builder Endowment    Endowment       12       55
3  LIC-MB-103       Milestone MoneyBack   Money Back       15       50
4   LIC-U-104        Wealth Maxima ULIP         ULIP        8       55

   min_coverage  max_coverage  premium_paying_term_min  \
0        500000      50000000                        1
1        250000      30000000                        5
2        100000      20000000                        5
3        150000      15000000                       10
4        500000      50000000                        5

   premium_paying_term_max                                        key_benefit  \
0                       40             High sum assured at extremely low cost
1                       30         Guaranteed lifetime coverage up to age 100
2                       25  Guaranteed maturity lump sum + accumulated bon...
3                       25  Regular survival payouts at predefined policy ...
4                       20  Dual benefit of life protection and equity/deb...

                                           benefit_2  \
0                      Accidental Death Rider option
1  Cash value accumulation with guaranteed additions
2                  Life cover during the policy term
3  Maturity payout of remaining sum assured with ...
4  Choice of 7+ investment funds ranging from deb...

                                           benefit_3 risk_profile  \
0     Option to increase coverage on life milestones          Low
1               Survival payout options after age 80          Low
2                      Critical illness rider add-on       Medium
3              Guaranteed additions in first 5 years       Medium
4  Partial withdrawal facility after 5 years lock-in         High

   base_premium_rate
0                1.1
1               12.0
2               35.0
3               45.0
4               15.0